apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisecow-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wisecow
  template:
    metadata:
      name: wisecow-pod
      labels:
        app: wisecow
    spec:
      containers:
      - name: wisecow
        image: virajdalave/wisecow:66f74636ef473efe5af3ec10d16836ca34fbe64d
        ports:
        - containerPort: 4499
