apiVersion: v1
kind: Service
metadata:
  name: wisecow-service
spec:
  type: LoadBalancer
  ports:
  - name: "http"
    port: 80
    protocol: TCP
    targetPort: 4499
  - name: "https"
    port: 443
    protocol: TCP
    targetPort: 4499
  selector:
    app: wisecow

