apiVersion: v1
kind: Service
metadata:
  name: wisecow-service
spec:
  type: ClusterIP
  ports:
  - name: "app-port"
    port: 4499
    protocol: TCP
    targetPort: 4499
  selector:
    app: wisecow

