apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisecow-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wisecow
  template:
    metadata:
      name: wisecow-pod
      labels:
        app: wisecow
    spec:
      containers:
      - name: wisecow
        image: virajdalave/wisecow:9bbebc8452743f0c3c6b49dcb17b92364d619e82
        ports:
        - containerPort: 4499
