apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisecow-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wisecow
  template:
    metadata:
      name: wisecow-pod
      labels:
        app: wisecow
    spec:
      containers:
      - name: wisecow
        image: virajdalave/wisecow:c100faacff8a75fcbd06164aa692204ed4cc46ed
        ports:
        - containerPort: 4499
