name: Deploy wisecow

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t virajdalave/wisecow:${{ github.sha }} .
        docker push virajdalave/wisecow:${{ github.sha }}

    - name: update image tag in k8s
      run: |
            sed -i "s|image: .*|image: ${{ secrets.DOCKER_USERNAME }}/wisecow:${{ github.sha }}|" kubernetes/wisecow-deployment.yaml
