name: Deploy wisecow

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t virajdalave/wisecow:latest .
        docker push virajdalave/wisecow:latest

    - name: Install kubectl
      run: |
        curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x ./kubectl
        sudo mv ./kubectl /usr/local/bin/kubectl

    - name: Update kubeconfig
      env:
        KUBECONFIG_B64: ${{ secrets.KUBECONFIG }}
      run: |
        mkdir -p ~/.kube
        echo "${KUBECONFIG_B64}" | base64 --decode > ~/.kube/config

    - name: Deploy to Kubernetes
      run: |
        cd kubernetes
        kubectl apply -f wisecow-deployment.yaml
        kubectl apply -f wisecow-service.yaml
